### PR TITLE
proposed fix for issue #30

### PR DESCRIPTION
**Pull request by messo**
Please check the issue and the commit which tries to fix it.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the pull request. I am a bit wary of `boolean pageChanged()` having a side-effect of changing the internal state of the object. Can you think of a way to refactor the code to be easier to follow?

I'll take a closer look at this perhaps later this week.

**Comment by messo** [comment]
well, pageChanged is only used in the iterator(); we could move this up to that point. If someone calls the iterator(int, int), we can be sure which part of the dataset she would like to retrieve. I consider this implication quite certain. What do you think?

**Comment by mattbrictson** [comment]
What do you think of the approach I've taken in 16ed3c3 ?

**Comment by messo** [comment]
LGTM, and definitely cleaner solution than mine! Thanks!

**Comment by mattbrictson** [comment]
See e4e0105ae7776147e09a99e0f46c13a55740ee0a.

**Pull request closed without merging**
